# Generated by Django 5.2.5 on 2026-01-31 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('psychologist', 'Психолог'), ('moderator', 'Модератор'), ('admin', 'Адміністратор')], default='user', max_length=15),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.specialization'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='years_of_exp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
