# Generated by Django 5.2.5 on 2025-12-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_psychologist_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='type_of_therapy',
            field=models.ManyToManyField(blank=True, to='accounts.typeoftherapy'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='languages',
            field=models.ManyToManyField(blank=True, to='accounts.language'),
        ),
    ]
