# Generated by Django 5.2.5 on 2026-01-05 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affirmations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmation',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_affirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='media',
            field=models.ImageField(upload_to='affirmations/'),
        ),
    ]
